import os

REG_USERNAME = os.getenv('REG_USERNAME')
REG_PASSWORD = os.getenv('REG_PASSWORD')

DIN_USERNAME = os.getenv('DIN_USERNAME')
DIN_PASSWORD = os.getenv('DIN_PASSWORD')

DIR_USERNAME = os.getenv('DIR_USERNAME')
DIR_PASSWORD = os.getenv('DIR_PASSWORD')

TRA_USERNAME = os.getenv('TRANSIT_USERNAME')
TRA_PASSWORD = os.getenv('TRANSIT_PASSWORD')

NEM_USERNAME = os.getenv('NEM_USERNAME')
NEM_PASSWORD = os.getenv('NEM_PASSWORD')

LIBCAL_ID = os.getenv('LIBCAL_ID')
LIBCAL_SECRET = os.getenv('LIBCAL_SECRET')

FITNESS_TOKEN = os.getenv('FITNESS_TOKEN')
